apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltakspenger-flate
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - {{ ingress }}
  replicas:
    min: 1
    max: 1
  azure:
    sidecar:
      enabled: true
      autoLogin: true
      openid.provider: "azure"
      errorPath: ""
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
      {{#if replyUrls}}
        replyURLs:
        {{#each replyUrls}}
          - {{ this }}
        {{\each}}
      {{\if}}
