apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tpts-soknad-flate
  namespace: tpts
  labels:
    team: tpts
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{image}}
  port: 3000
  ingresses:
    {{#each ingresses}}
       - {{this}}
      {{/each}}
  replicas:
    min: 1
    max: 1
  azure:
    sidecar:
      enabled: true
      autoLogin: false
      errorPath: ""
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
        # groups:
        #  - id: "de1a64fd-70d7-4cb2-84e9-6c9fdf948f1b" # TPTS i Azure AD
  env:
    - name: CORS_DOMAIN
      value: "*"