apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltakspenger-flate
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://tiltakspenger-flate.dev.intern.nav.no
  replicas:
    min: 1
    max: 1
  azure:
    sidecar:
      enabled: true
      autoLogin: true
      openid.provider: "azure"
      errorPath: ""
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
        # groups:
        #  - id: "de1a64fd-70d7-4cb2-84e9-6c9fdf948f1b" # TPTS i Azure AD
      replyURLs:
        - "https://tiltakspenger-flate.dev.intern.nav.no/oauth2/callback"
        - "http://127.0.0.1:3000/oauth2/callback"
  env:
    - name: CORS_DOMAIN
      value: "*"
    - name: OBO_SCOPE
      value: "api://eafda703-c821-44de-990c-950dec1ad22f/.default"
    - name: BACKEND_URL
      value: "https://tiltakspenger-vedtak.dev.intern.nav.no"
