apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tpts-tiltakspenger-flate
  namespace: tpts
  labels:
    team: tpts
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://tpts-tiltakspenger-flate.dev.intern.nav.no
  replicas:
    min: 1
    max: 1
  azure:
    sidecar:
      enabled: true
      autoLogin: true
      openid.provider: "azure"
      errorPath: ""
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
        # groups:
        #  - id: "de1a64fd-70d7-4cb2-84e9-6c9fdf948f1b" # TPTS i Azure AD
      replyURLs:
        - "https://tpts-tiltakspenger-flate.dev.intern.nav.no/oauth2/callback"
        - "http://127.0.0.1:3000/oauth2/callback"
  envFrom:
    - configmap: tpts-tiltakspenger-flate-dev
  env:
    - name: CORS_DOMAIN
      value: "*"