name: Update GitHub Pages
on:
  push:
    branches:
      - main
env:
  CI: true
  TZ: Europe/Amsterdam
  PUBLIC_URL: /tiltakspenger-flate

jobs:
  update-gh-pages:
    name: Update GitHub pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Build mock application
        run: npm run build-mock-gh-pages
      - name: Update GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build